### ISSUE TITLE
Support for symfony 3.4.x

### ISSUE THREAD

**Issue by Mattia1993** [fxpio/fxp-security-bundle#19]
Hi,
ive used this bundle in a project using  Symfony 3.3.x and it worked very well!!!
Now i would like to use the same bundle on a version of Symfony 3.4.13 but after the last commit that changed the support to Symfony 4.1 i cant use it anymore.
So im asking if there is a chance to release a tag for keep the support to Symfony 3.4.13 and lower versions.

Thanks in advance

**Comment by francoispluchino** [comment]
Indeed, the minimum support for the first stable version will be 4.1. Given that the bundle was in development, and knowing that this bundle is very specific, so little used, I could afford to change the constraints to avoid adding support for older versions of Symfony. Because I just do not have enough time to maintain all the old versions. The stable versions will be available in the next few days, but in your case, you can use the SHA in the constraints to continue using this bundle with previous versions of Symfony:

```json
{
  "require": {
    "fxp/security": "dev-master#127a1dc04e04750ef5d18a990fc5c263f41d29c6",
    "fxp/security-bundle": "dev-master#44aea2bc6b898bcf61556b6024b48e857ed2d411"
  }
}
```

**Comment by Mattia1993** [comment]
Hi, i wasnt asking to support actively the development for Symfony 3.4.* ive just asked for a tag that indicate the end of the support for that release of Symfony.

Your solution was the first that ive tried but it seems that doesnt work and gives me the warning as follows:

>- fxp/security-bundle dev-master requires fxp/security ^1.0.0 -> satisfiable by fxp/security[1.0.x-dev].
>- Conclusion: remove symfony/symfony v3.4.14
>- Conclusion: don't install symfony/symfony v3.4.14
>- Conclusion: don't install symfony/symfony v3.4.13
>- Conclusion: don't install symfony/symfony v3.4.12
>- Conclusion: don't install symfony/symfony v3.4.11
>- Conclusion: don't install symfony/symfony v3.4.10
>- Conclusion: don't install symfony/symfony v3.4.9
>- Conclusion: don't install symfony/symfony v3.4.8
>- Conclusion: don't install symfony/symfony v3.4.7
>- Conclusion: don't install symfony/symfony v3.4.6
>- Conclusion: don't install symfony/symfony v3.4.5
>- Conclusion: don't install symfony/symfony v3.4.4
>- Conclusion: don't install symfony/symfony v3.4.3
>- Conclusion: don't install symfony/symfony v3.4.2
>- Conclusion: don't install symfony/symfony v3.4.1
>- Conclusion: don't install symfony/symfony v3.4.0
>- Conclusion: don't install symfony/symfony v3.4.0-RC2
>- Conclusion: don't install symfony/symfony v3.4.0-RC1
>- Conclusion: don't install symfony/symfony v3.4.0-BETA4
>- Conclusion: don't install symfony/symfony v3.4.0-BETA3
>- Installation request for fxp/security-bundle dev-master#44aea2bc6b898bcf61556b6024b48e857ed2d411 -> satisfiable by fxp/security-bundle[dev-master].
>- Conclusion: don't install symfony/symfony v3.4.0-BETA2
>- Conclusion: don't install symfony/symfony v3.4.0-BETA1
>- fxp/security 1.0.x-dev requires symfony/expression-language ^4.1.0 -> satisfiable by symfony/expression-language[4.1.x-dev, 4.2.x-dev, v4.1.0, v4.1.0-BETA1, v4.1.0-BETA2, v4.1.0-BETA3, v4.1.1, v4.1
.2, v4.1.3].
>- don't install symfony/expression-language 4.1.x-dev|don't install symfony/symfony 3.4.x-dev
>- don't install symfony/expression-language 4.2.x-dev|don't install symfony/symfony 3.4.x-dev
>- don't install symfony/expression-language v4.1.0|don't install symfony/symfony 3.4.x-dev
>- don't install symfony/expression-language v4.1.0-BETA1|don't install symfony/symfony 3.4.x-dev
>- don't install symfony/expression-language v4.1.0-BETA2|don't install symfony/symfony 3.4.x-dev
>- don't install symfony/expression-language v4.1.0-BETA3|don't install symfony/symfony 3.4.x-dev
>- don't install symfony/expression-language v4.1.1|don't install symfony/symfony 3.4.x-dev
>- don't install symfony/expression-language v4.1.2|don't install symfony/symfony 3.4.x-dev
>- don't install symfony/expression-language v4.1.3|don't install symfony/symfony 3.4.x-dev
>- Installation request for symfony/symfony 3.4.* -> satisfiable by symfony/symfony[3.4.x-dev, v3.4.0, v3.4.0-BETA1, v3.4.0-BETA2, v3.4.0-BETA3, v3.4.0-BETA4, v3.4.0-RC1, v3.4.0-RC2, v3.4.1, v3.4.10,
v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].

Any help would be appreciated.

**Comment by francoispluchino** [comment]
Ok, I see the problem... That's because Composer doesn't know about the composer.json file for this specific hash. This behavior exist, because Packagist only stores the latest composer.json for the `dev-master` (see the blue note of the [doc](https://getcomposer.org/doc/04-schema.md#package-links)). So, Composer cannot installed the good versions, when the constraints have changed.

As a result, I have created a new tag `v1.0.0-alpha1` for Symfony 3.4 and `v1.0.0` for Symfony 4.1.

Now, you can use these constraints:

```json
{
  "require": {
    "symfony/symfony": "^3.4.0",
    "fxp/security": "^1.0.0@alpha",
    "fxp/security-bundle": "^1.0.0@alpha"
  }
}
```
